### ISSUE TITLE
[Tangram R&D] Include Tangram.js in this bundle

### ISSUE THREAD

**Issue by donflopez** [CartoDB/tangram.cartodb#10]
To have a complete bundle without external dependencies, we have to include tangram in this bundle, this is now possible.

**Comment by dgaubert** [comment]
Please, could you provide acceptance steps?

**Comment by donflopez** [comment]
## Acceptance

1.- Clone the repo
2.- Checkout to the branch `tangramjs-bundle`
3.- Install deps `yarn install`
4.- Execute dev `yarn start`
5.- Go to the address and check that it works as expected clicking in GO and going to Paris for checking that the points are rendered.

**Comment by dgaubert** [comment]
Hey!

I had some troubles following acceptance steps, I was able to open the provided URL but clicking in GO did not work as expected, it did nothing:

<img width="641" alt="screen shot 2017-06-06 at 12 04 44" src="https://cloud.githubusercontent.com/assets/1936888/26824220/bfd71f38-4ab0-11e7-9a07-f429ef95b5a1.png">

Console output:

![screen shot 2017-06-06 at 12 08 46](https://cloud.githubusercontent.com/assets/1936888/26824260/f202bd96-4ab0-11e7-882a-a297b938e32e.png)

@donflopez, Do you know what I did wrong?

**Comment by dgaubert** [comment]
Passed 💥 

![screen shot 2017-06-06 at 18 09 11](https://user-images.githubusercontent.com/1936888/26839463-5bed6d3c-4ae3-11e7-9abc-75fc83aa8a99.png)

Thanks @donflopez for the help!

**Comment by donflopez** [comment]
Thanks to you! Your acceptance helped a lot! 💋

**Comment by rafatower** [comment]
Already deployed in prod, as per this reference:

https://github.com/CartoDB/cartodb/blob/165f984d7f83e041f0acc17e40981a781bd86033/npm-shrinkwrap.json#L3081
