### ISSUE TITLE
Embed is not rendering

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/tangram.cartodb#2]
https://team.carto.com/u/piensaenpixel/builder/72a358fe-0894-11e5-9e8a-0e018d66dc29/embed?vector=true

**Comment by donflopez** [comment]
This bug is because the use of allow-overlap with a condition (tangram doesn't support it).

We have to think about what could be the best solution.

**Comment by donflopez** [comment]
Fix is here https://github.com/CartoDB/tangram-carto/issues/37

**Comment by donflopez** [comment]
Fixed!
